### ISSUE TITLE
Should the "children" element of _AbstractBuilding point to ThermalZone/UsageZone?

### ISSUE THREAD

**Issue by ozgetufan** [ozgetufan/cjenergy#4]
Right now, "parent" element of ThermalZone points to the Building. Is it necessary to do the other way around?

**Comment by kenohori** [comment]
My guess is yes, since the most common use case would involve starting from a building and getting its thermal zones? I think that makes much more sense than the opposite (start from a thermal zone and get what building it belongs to).
