### ISSUE TITLE
How to map WeatherData "position" attribute with GM_Point type?

### ISSUE THREAD

**Issue by ozgetufan** [ozgetufan/cjenergy#6]
I defined WeatherData as a JSON object in the definitions part. Its position attribute has the GM_Point value, which is not possible to map to CityJSON. I can omit this attribute, or maybe define WeatherData instead as an extraCityObject so that its geometry property can be used?

**Comment by kenohori** [comment]
for reference: https://www.cityjson.org/specs/1.1.0/#geometry-templates

to summarise the two ideas:
* include geometry with boundary consisting of a single vertex ID, or
* use the same mechanism (link to vertex by ID) in another attribute
